### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by akrishna0** [bounceur/CupCarbon#15]
Please provide the links where it is written to follow this link.

**Comment by bounceur** [comment]
Please, can you give more details about the place where this is written?
Thx

Le mer. 30 sept. 2020 à 11:03, Akash Krishna <notifications@github.com> a
écrit :

**Comment by akrishna0** [comment]
In the Installation Section
1st point 
- Download the source code  form our GitHub (or use the link bellow) - Choose clone or download -> Download ZIP

**Comment by bounceur** [comment]
The link is given and you have just to click on GitHub (not below!, sorry
for that) : https://github.com/bounceur/CupCarbon

Le mer. 30 sept. 2020 à 21:03, Akash Krishna <notifications@github.com> a
écrit :

**Comment by akrishna0** [comment]
It is not working while clicking on GitHub please update it.
- And please provide the documentation for the installation on different platforms 
- and executable files also.

**Comment by bounceur** [comment]
The link works normally: http://cupcarbon.com/src_download.html
The installation works normally on windows and apple. It works also on
linux, you need to install javafx.
Please, give me more details on your situation so I can help.
The executable is online: http://cupcarbon.com/download.html

Le lun. 5 oct. 2020 à 09:34, Akash Krishna <notifications@github.com> a
écrit :

**Comment by akrishna0** [comment]
Thank you for the links issue has been resolved
