### ISSUE TITLE
Passing parameter to a function still needs $ symbol

### ISSUE THREAD

**Issue by micdic** [bounceur/CupCarbon#20]
It seems that the call to a function, i.e.

set d 10
res function myf d

using CupCarbon v5, still requires $ symbol to extract value.
In this example the function myf() receives the value "d", not 10.

Instead, if i use
set d 10
res function myf $d

the function myf() correctly receives the value 10.

**Comment by bounceur** [comment]
Hi Michele,
Thanks for choosing CupCarbon.
Really I appreciate your remark. You are right, there is a bug in this part
that we have missed.
Please, just correct this part and we will update it as soon as possible on
our website:
Go to the package : senscript
Search the class: SenScript (Senscript.java)
Search the method: variablesToValues
And replace it by the following one:

public void variablesToValues(String [] args) {
for(int i=0; i<args.length; i++)
args[i] = getVariableValue(args[i]);
}


Best regards,
Ahcène

Le sam. 30 oct. 2021 à 11:19, Michele Di Capua ***@***.***> a
écrit :

**Comment by micdic** [comment]
It works perfeclty now.

Thanks Ahcène.
Best Regards.
